name: solidity-tests-action
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run RobinWood solidity tests
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        run: npm install
      - name: Run tests
        run: npm test
